name: ESPHome Builder
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        GIT_VERSION=$(git describe --tags --always --dirty)
        sed -i "s/GIT_VERSION_FIELD/$GIT_VERSION/g" osmobuddy.yaml
    - name: ESPHome Builder
      uses: esphome/build-action@v7.2.0
      with:
        yaml-file: osmobuddy.yaml
